name: Android CI

on:
  push:
    branches:
      - main

env:
  ANDROID_HOME: /usr/local/android-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Android SDK
        uses: actions/setup-android@v1
        with:
          android-version: 28
          sdk-channel: stable

      - name: Run tests
        run: ./gradlew test

      - name: Build apk
        run: ./gradlew assembleDebug
